#!/bin/bash

set -euo pipefail

# VERBOSE MODE (0=quiet, 1=verbose)
VERBOSE=${VERBOSE:-1}

# FORCE CI MODE FOR DETERMINISTIC OUTPUT (DISABLE UPDATE CHECKS, MASK IPS)
export CI=1

# RUN MODES (1=ENABLED, 0=DISABLED)
RUN_AUTOTOOLS_TEST=${RUN_AUTOTOOLS_TEST:-1}
RUN_AUTOTOOLS_SMOKE=${RUN_AUTOTOOLS_SMOKE:-1}

# CREATE DOWNLOAD DIRECTORY
BASE_WORKDIR=${BASE_WORKDIR:-/data/downloads}

# USE A UNIQUE WORKDIR PER PLATFORM+PYTHON TO AVOID COLLISIONS
PLATFORM_SAFE=${PLATFORM:-unknown}
PY_SAFE=${PYTHON_VERSION:-unknown}
WORKDIR=${WORKDIR:-${BASE_WORKDIR}/${PLATFORM_SAFE}-py${PY_SAFE}}

# ISOLATE PYTEST ARTIFACTS PER CONTAINER (AVOID .coverage/.pytest_cache COLLISIONS)
# DEFAULT TO /tmp TO AVOID POLLUTING THE REPO (BIND-MOUNT) AND docker/data/
TEST_BASE_WORKDIR=${TEST_BASE_WORKDIR:-/tmp/autotools-tests}
TEST_WORKDIR=${TEST_WORKDIR:-${TEST_BASE_WORKDIR}/${PLATFORM_SAFE}-py${PY_SAFE}}

# CREATE WORKDIR
mkdir -p "$WORKDIR"
mkdir -p "$TEST_WORKDIR"

# KEEP PYTHON BYTECODE AND PYTEST CACHE OUT OF THE REPO BIND-MOUNT
export PYTHONDONTWRITEBYTECODE=1
export COVERAGE_FILE=${COVERAGE_FILE:-${TEST_WORKDIR}/.coverage}
export PYTEST_ADDOPTS="-o cache_dir=${TEST_WORKDIR}/.pytest_cache ${PYTEST_ADDOPTS:-}"

# PRINT BASIC RUNTIME INFO (HELPS DEBUG)
echo "Running AutoTools tests..."
echo "Platform: ${PLATFORM:-unknown}"
echo "Python: $(python --version 2>&1)"
echo "Workdir: $WORKDIR"
echo "Test workdir: $TEST_WORKDIR"

# RUN FULL PYTEST SUITE FIRST (MATCHES publish.yml PYTHON MATRIX INTENT)
if [ "$RUN_AUTOTOOLS_TEST" = "1" ]; then
  autotools test
fi

# RUN SMOKE TESTS AFTER (CLI-LEVEL VALIDATION)
if [ "$RUN_AUTOTOOLS_SMOKE" = "1" ]; then
  if [ "$VERBOSE" = "1" ]; then
    autotools smoke --workdir "$WORKDIR" --verbose
  else
    autotools smoke --workdir "$WORKDIR" --quiet
  fi
fi

# PRINT SUCCESS MESSAGE
echo -e "\nAll tests completed!"
